

import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ClientProvider } from './Providers'




export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
   <ClientProvider>

    <html lang="en">
      <body >{children}</body>
    </html>


   </ClientProvider>


  )
}
